services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8900:80"
    volumes: 
      - ./nginx:/etc/nginx/conf.d/

  postgres:
    image: postgres
    container_name: designoop-postgres
    environment:
      POSTGRES_USER: prodUser
      POSTGRES_PASSWORD: prodPassword
      POSTGRES_DB: DesignOOP-UsersDB
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users-module:
    image: designoop-users-module
    container_name: designoop-users-module
    depends_on:
      - postgres
    build:
      context: ./backend/users-module
    expose:
      - "8083"
    ports:
      - "8083:8083"
    env_file:
      - ./backend/users-module/.env.docker.dev


  mongodb:
    image: mongo:latest
    container_name: designoop-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: designoop-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: designoop-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1234
      ME_CONFIG_MONGODB_URL: mongodb://root:pass1234@designoop-mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8082:8081"
    depends_on:
      - mongodb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    expose:
      - "80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dragos.dev12@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminPass
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  courses-module:
    image: designoop-courses-module
    container_name: designoop-courses-module
    depends_on:
      - mongodb
    build:
      context: ./backend/courses-module
    expose:
      - "8081"
    ports:
      - "8081:8081"
    env_file:
      - ./backend/courses-module/.env.docker.dev

  frontend: #nextjs
    container_name: designoop-frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.local
    image: designoop-frontend
    depends_on:
      - users-module
      - courses-module
    ports:
      - "3000:3000"

volumes:
  mongodb_data: {}
  postgres_data: {}
  pgadmin_data: {}