server.port: 8083

spring:
  profiles:
    active: @activatedProperties@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: DesignOOP-UsersPool
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

server:
  error:
    include-message: always