/* eslint-disable no-template-curly-in-string */
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rOVQPOOOOQO'#Cb'#CbOnQPO'#CeO|QPO'#CoOOQO'#Cu'#CuQOQPOOOOQO'#Cg'#CgO!TQPO'#CfO!YQPO'#CyOOQO'#Cx'#CxO!hQPO,59WO!sQPO,59PO!xQPO'#DQOOQO,59Z,59ZO#QQPO,59ZOVQPO,59QO#VQPO'#CpO#[QPO,59eOOQO'#Ci'#CiO#jQPO'#ChOOQO'#Ck'#CkO#oQPO'#CjO#tQPO,59cO$PQPO'#DPO$XQPO,59cOOQO1G.r1G.rOOQO1G.k1G.kOVQPO'#CqO$aQPO,59lOOQO1G.u1G.uOOQO1G.l1G.lOOQO,59[,59[OOQO-E6n-E6nOVQPO,59SOVQPO,59UO$iQPO1G.}O$qQPO,59kOOQO1G.}1G.}OOQO,59],59]OOQO-E6o-E6oOOQO1G.n1G.nOOQO1G.p1G.pOOQO1G/S1G/SOOQO1G/V1G/V",
  stateData: "${~OhOS~OQSORSOSSOTSOWQObROjPO~OjUOVlPqlPrlP~Oa]O~PVOn_O~Oo`OVmXqmXrmX~OViOqbOrdO~OVjO~OokOatX~OamO~OjUO~Oo`OVmaqmarma~OnqO~OnrO~OjUOVlPrlP~OjUOqlP~OjUOVlP~OokOata~OrdOVki~OqbO~Oqrjr~",
  goto: "$PuPPPPPPvPPv!O!X!`!f!j!pvPPv!t!zPPP#QP#d#g#sPP#yPP#y#|]SOR_kqrWWQfghRo`ZVQ`fghQfYR{tTcYtQgYRzsTeYsQaWRpaQl[RwlQTOQ[RQn_QvkQxqRyrRZQQYQQsfQtgRuhXXQfghRhYR^R",
  nodeNames: "⚠ JsonText True False Null Number String } { Component Property PropertyName ComponentTypeProperty ComponentTypePropertyName ChildrenProperty ChildrenPropertyName Object ] [ Array",
  maxTerm: 36,
  nodeProps: [
    ["openedBy", 7,"{",17,"["],
    ["closedBy", 8,"}",18,"]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "8X~RaXY!WYZ!W]^!Wpq!Wrs!]|}4Q}!O4V!Q!R4`!R![5n![!]6P!}#O6U#P#Q6Z#Y#Z6`#b#c6}#h#i7f#o#p7}#q#r8S~!]Oh~~!`Ypq#Oqr#Ors#ks#O#O#O#P#p#P#V#O#V#W%h#W;'S#O;'S;=`%b<%lO#O~#RWpq#Oqr#Ors#ks#O#O#O#P#p#P;'S#O;'S;=`%b<%lO#O~#pOj~~#sXrs#O!P!Q#O#O#P#O#U#V#O#Y#Z#O#b#c#O#f#g#O#h#i#O#i#j$`~$cR!Q![$l!c!i$l#T#Z$l~$oR!Q![$x!c!i$x#T#Z$x~${R!Q![%U!c!i%U#T#Z%U~%XR!Q![#O!c!i#O#T#Z#O~%eP;=`<%l#O~%k[pq#Oqr#Ors#ks#O#O#O#P#p#P#[#O#[#]&a#]#c#O#c#d+c#d;'S#O;'S;=`%b<%lO#O~&dYpq#Oqr#Ors#ks#O#O#O#P#p#P#]#O#]#^'S#^;'S#O;'S;=`%b<%lO#O~'VYpq#Oqr#Ors#ks#O#O#O#P#p#P#`#O#`#a'u#a;'S#O;'S;=`%b<%lO#O~'xYpq#Oqr#Ors#ks#O#O#O#P#p#P#W#O#W#X(h#X;'S#O;'S;=`%b<%lO#O~(kYpq#Oqr#Ors#ks#O#O#O#P#p#P#f#O#f#g)Z#g;'S#O;'S;=`%b<%lO#O~)^Ypq#Oqr#Ors#ks#O#O#O#P#p#P#X#O#X#Y)|#Y;'S#O;'S;=`%b<%lO#O~*PYpq#Oqr#Ors#ks#O#O#O#P#p#P#b#O#b#c*o#c;'S#O;'S;=`%b<%lO#O~*rWpq#Oqr#Ors+[s#O#O#O#P#p#P;'S#O;'S;=`%b<%lO#O~+cOr~j~~+fYpq#Oqr#Ors#ks#O#O#O#P#p#P#a#O#a#b,U#b;'S#O;'S;=`%b<%lO#O~,XYpq#Oqr#Ors#ks#O#O#O#P#p#P#d#O#d#e,w#e;'S#O;'S;=`%b<%lO#O~,zYpq#Oqr#Ors#ks#O#O#O#P#p#P#c#O#c#d-j#d;'S#O;'S;=`%b<%lO#O~-mYpq#Oqr#Ors#ks#O#O#O#P#p#P#b#O#b#c.]#c;'S#O;'S;=`%b<%lO#O~.`Ypq#Oqr#Ors#ks#O#O#O#P#p#P#X#O#X#Y/O#Y;'S#O;'S;=`%b<%lO#O~/RYpq#Oqr#Ors#ks#O#O#O#P#p#P#b#O#b#c/q#c;'S#O;'S;=`%b<%lO#O~/tYpq#Oqr#Ors#ks#O#O#O#P#p#P#h#O#h#i0d#i;'S#O;'S;=`%b<%lO#O~0gYpq#Oqr#Ors#ks!v#O!v!w1V!w#O#O#O#P#p#P;'S#O;'S;=`%b<%lO#O~1YYpq#Oqr#Ors#ks#O#O#O#P#p#P#m#O#m#n1x#n;'S#O;'S;=`%b<%lO#O~1{Ypq#Oqr#Ors#ks#O#O#O#P#p#P#d#O#d#e2k#e;'S#O;'S;=`%b<%lO#O~2nYpq#Oqr#Ors#ks#O#O#O#P#p#P#X#O#X#Y3^#Y;'S#O;'S;=`%b<%lO#O~3aWpq#Oqr#Ors3ys#O#O#O#P#p#P;'S#O;'S;=`%b<%lO#O~4QOq~j~~4VOo~~4YQ!Q!R4`!R![5n~4eRT~!O!P4n!g!h5S#X#Y5S~4qP!Q![4t~4yRT~!Q![4t!g!h5S#X#Y5S~5VR{|5`}!O5`!Q![5f~5cP!Q![5f~5kPT~!Q![5f~5sST~!O!P4n!Q![5n!g!h5S#X#Y5S~6UOn~~6ZOb~~6`Oa~~6cP#T#U6f~6iP#`#a6l~6oP#g#h6r~6uP#X#Y6x~6}OR~~7QP#i#j7T~7WP#`#a7Z~7^P#`#a7a~7fOS~~7iP#f#g7l~7oP#i#j7r~7uP#X#Y7x~7}OQ~~8SOW~~8XOV~",
  tokenizers: [0],
  topRules: {"JsonText":[0,1]},
  tokenPrec: 176
})
