// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  JsonText = 1,
  True = 2,
  False = 3,
  Null = 4,
  Number = 5,
  String = 6,
  Component = 9,
  GraphicProperty = 10,
  GraphicPropertyName = 11,
  Property = 12,
  PropertyName = 13,
  ComponentTypeProperty = 14,
  ComponentTypePropertyName = 15,
  ChildrenProperty = 16,
  ChildrenPropertyName = 17,
  Object = 18,
  Array = 21
