server.port: 8081
spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${mongodb_username}
      password: ${mongodb_password}
      database: ${mongodb_database}
      host: ${mongodb_host}
      port: ${mongodb_port}

server:
  error:
    include-message: always
